import { mkdir, writeFile, stat } from 'node:fs/promises';
import path from 'node:path';
import type {
  ExportCanvasNode,
  ExportCanvasPayload,
  ExportCanvasResult,
  ScaffoldFullstackPayload,
  ScaffoldFullstackResult
} from '../../src/common/ipc';

async function pathExists(p: string): Promise<boolean> {
  try {
    await stat(p);
    return true;
  } catch {
    return false;
  }
}

async function ensureDir(p: string): Promise<void> {
  await mkdir(p, { recursive: true });
}

async function writeGenerated(
  root: string,
  rel: string,
  content: string,
  overwrite: boolean,
  created: string[]
): Promise<void> {
  const file = path.join(root, rel);
  if ((await pathExists(file)) && !overwrite) {
    throw new Error(`File already exists and overwrite is disabled: ${rel}`);
  }
  await ensureDir(path.dirname(file));
  await writeFile(file, content, 'utf8');
  created.push(file);
}

function validateProjectName(name: string): string {
  const normalized = name.trim();
  if (!normalized) throw new Error('Project name is required.');
  if (!/^[a-zA-Z0-9_-]+$/.test(normalized)) {
    throw new Error('Project name can only include letters, numbers, hyphens, and underscores.');
  }
  return normalized;
}

function safeHandlerName(method: string, p: string): string {
  const safe = p
    .replace(/^\/+/, '')
    .replace(/[^a-zA-Z0-9]+(.)/g, (_, c: string) => c.toUpperCase())
    .replace(/[^a-zA-Z0-9]/g, '');
  const fallback = safe.length > 0 ? safe : 'Root';
  return `${method.toLowerCase()}${fallback.charAt(0).toUpperCase()}${fallback.slice(1)}`;
}

function normalizePath(value: string): string {
  const normalized = value.trim().replace(/\s+/g, '-').replace(/\/+/g, '/');
  if (!normalized) return '/api/resource';
  return normalized.startsWith('/') ? normalized : `/${normalized}`;
}

function buildExpressRoutes(openApiJson?: string): string | null {
  if (!openApiJson?.trim()) return null;
  try {
    const parsed = JSON.parse(openApiJson) as {
      paths?: Record<string, Record<string, { summary?: string; description?: string; security?: unknown }>>;
    };
    const lines: string[] = [
      "const express = require('express');",
      '',
      'const router = express.Router();',
      '',
      'function requireAuth(req, res, next) {',
      '  if (!req.headers.authorization) {',
      "    return res.status(401).json({ error: 'Unauthorized' });",
      '  }',
      '  return next();',
      '}',
      ''
    ];
    const methods = ['get', 'post', 'put', 'patch', 'delete'] as const;
    for (const [endpointPathRaw, methodMap] of Object.entries(parsed.paths ?? {})) {
      const endpointPath = normalizePath(endpointPathRaw);
      for (const method of methods) {
        const op = methodMap?.[method];
        if (!op) continue;
        const handler = safeHandlerName(method, endpointPath);
        const requiresAuth = Array.isArray(op.security) && op.security.length > 0;
        if (op.summary) lines.push(`// ${op.summary}`);
        if (op.description) lines.push(`// ${op.description}`);
        lines.push(`async function ${handler}(req, res) {`);
        lines.push('  const payload = req.method === "GET" ? req.query : req.body;');
        lines.push(
          `  return res.status(200).json({ ok: true, method: '${method.toUpperCase()}', route: '${endpointPath}', payload });`
        );
        lines.push('}');
        lines.push(`router.${method}('${endpointPath}'${requiresAuth ? ', requireAuth' : ''}, ${handler});`);
        lines.push('');
      }
    }
    if (lines.length <= 12) return null;
    lines.push('module.exports = router;');
    lines.push('');
    return lines.join('\n');
  } catch {
    return null;
  }
}

export async function scaffoldFullstackProject(
  payload: ScaffoldFullstackPayload
): Promise<ScaffoldFullstackResult> {
  try {
    const projectName = validateProjectName(payload.projectName);
    const targetRoot = payload.targetRoot.trim();
    if (!targetRoot) return { ok: false, createdFiles: [], error: 'Target root is required.' };
    const projectRoot = path.join(targetRoot, projectName);
    const overwrite = !!payload.overwrite;
    if ((await pathExists(projectRoot)) && !overwrite) {
      return { ok: false, createdFiles: [], error: `Project folder already exists: ${projectRoot}` };
    }
    await ensureDir(projectRoot);
    const created: string[] = [];

    await writeGenerated(
      projectRoot,
      'README.md',
      `# ${projectName}\n\nGenerated by AetherForge IDE.\n\n## Stack\n- Frontend: React + TypeScript\n- Backend: ${payload.backend}\n- Database: ${payload.database}\n`,
      overwrite,
      created
    );

    await writeGenerated(
      projectRoot,
      'frontend/package.json',
      JSON.stringify(
        {
          name: `${projectName}-frontend`,
          private: true,
          version: '0.1.0',
          scripts: { dev: 'vite', build: 'vite build' },
          dependencies: { react: '^18.3.0', 'react-dom': '^18.3.0' },
          devDependencies: { vite: '^5.4.0', '@vitejs/plugin-react': '^4.3.0' }
        },
        null,
        2
      ),
      overwrite,
      created
    );

    await writeGenerated(
      projectRoot,
      'frontend/src/main.tsx',
      `import React from 'react';\nimport ReactDOM from 'react-dom/client';\n\nfunction App() {\n  return <h1>AetherForge Generated Frontend</h1>;\n}\n\nReactDOM.createRoot(document.getElementById('root')!).render(<App />);\n`,
      overwrite,
      created
    );

    if (payload.backend === 'express') {
      const generated = buildExpressRoutes(payload.generatedArtifacts?.openApiJson);
      await writeGenerated(
        projectRoot,
        'backend/package.json',
        JSON.stringify(
          {
            name: `${projectName}-backend`,
            private: true,
            version: '0.1.0',
            scripts: { dev: 'node src/server.js', start: 'node src/server.js' },
            dependencies: { express: '^4.19.2' }
          },
          null,
          2
        ),
        overwrite,
        created
      );
      await writeGenerated(
        projectRoot,
        'backend/src/server.js',
        `const express = require('express');\nconst routes = require('./routes');\n\nconst app = express();\napp.use(express.json());\napp.use('/api', routes);\napp.get('/health', (_, res) => res.json({ ok: true }));\n\napp.listen(4000, () => console.log('Server listening on 4000'));\n`,
        overwrite,
        created
      );
      await writeGenerated(
        projectRoot,
        'backend/src/routes/index.js',
        generated ??
          `const express = require('express');\n\nconst router = express.Router();\n\nrouter.get('/users', async (_req, res) => {\n  return res.status(200).json({ data: [{ id: '1', email: 'demo@aetherforge.dev' }] });\n});\n\nmodule.exports = router;\n`,
        overwrite,
        created
      );
    } else {
      await writeGenerated(
        projectRoot,
        'backend/requirements.txt',
        'fastapi==0.116.0\nuvicorn==0.35.0\n',
        overwrite,
        created
      );
      await writeGenerated(
        projectRoot,
        'backend/app/main.py',
        `from fastapi import FastAPI\nfrom .routers.users import router as users_router\n\napp = FastAPI()\napp.include_router(users_router, prefix='/api')\n\n@app.get('/health')\ndef health():\n    return {'ok': True}\n`,
        overwrite,
        created
      );
      await writeGenerated(
        projectRoot,
        'backend/app/routers/users.py',
        `from fastapi import APIRouter\nfrom ..services.users import get_users\n\nrouter = APIRouter()\n\n@router.get('/users')\ndef list_users():\n    return {'data': get_users()}\n`,
        overwrite,
        created
      );
      await writeGenerated(
        projectRoot,
        'backend/app/services/users.py',
        `def get_users():\n    return [{'id': '1', 'email': 'demo@aetherforge.dev'}]\n`,
        overwrite,
        created
      );
      await writeGenerated(
        projectRoot,
        'backend/app/schemas/user.py',
        `from pydantic import BaseModel\n\nclass User(BaseModel):\n    id: str\n    email: str\n`,
        overwrite,
        created
      );
    }

    if (payload.database === 'prisma' || payload.database === 'both') {
      await writeGenerated(
        projectRoot,
        'backend/prisma/schema.prisma',
        payload.generatedArtifacts?.prismaSchema?.trim() ||
          `generator client {\n  provider = "prisma-client-js"\n}\n\ndatasource db {\n  provider = "postgresql"\n  url      = env("DATABASE_URL")\n}\n\nmodel User {\n  id        String   @id @default(cuid())\n  email     String   @unique\n  createdAt DateTime @default(now())\n}\n`,
        overwrite,
        created
      );
    }

    if (payload.database === 'supabase' || payload.database === 'both') {
      await writeGenerated(
        projectRoot,
        'backend/supabase/migrations/001_initial.sql',
        payload.generatedArtifacts?.supabaseSql?.trim() ||
          `create table if not exists public.users (\n  id uuid primary key default gen_random_uuid(),\n  email text not null unique,\n  created_at timestamptz not null default now()\n);\n`,
        overwrite,
        created
      );
      await writeGenerated(
        projectRoot,
        'backend/supabase/config.toml',
        `[project]\nname = "aetherforge-generated"\n`,
        overwrite,
        created
      );
    }

    await writeGenerated(
      projectRoot,
      '.env.example',
      `DATABASE_URL=postgresql://user:password@localhost:5432/app\nSUPABASE_URL=https://your-project.supabase.co\nSUPABASE_ANON_KEY=your-anon-key\n`,
      overwrite,
      created
    );

    return { ok: true, projectPath: projectRoot, createdFiles: created };
  } catch (err) {
    return {
      ok: false,
      createdFiles: [],
      error: err instanceof Error ? err.message : 'Failed to scaffold full-stack project'
    };
  }
}

// ─── Canvas export ──────────────────────────────────────────────────────────

function nodeToReactJsx(node: ExportCanvasNode): string {
  const { componentType, label, x, y, props } = node;
  const style = `{{ position:'absolute', left:${x}, top:${y}${props.width ? `, width:${props.width}` : ''}${
    props.height ? `, height:${props.height}` : ''
  }${props.backgroundColor ? `, backgroundColor:'${props.backgroundColor}'` : ''}${
    props.padding ? `, padding:${props.padding}` : ''
  } }}`;
  const cls = props.className ?? '';
  switch (componentType) {
    case 'button':
      return `      <button style={${style}} className="${cls || 'rounded-md bg-cyan-500 px-3 py-2 text-white'}">${props.text ?? label}</button>`;
    case 'text':
      return `      <p style={${style}} className="${cls || 'text-base text-slate-100'}">${props.text ?? label}</p>`;
    case 'image':
      return `      <img style={${style}} src="${props.src ?? ''}" alt="${label}" className="${cls}" />`;
    case 'card':
      return `      <div style={${style}} className="${cls || 'rounded-lg border border-slate-500/40 bg-slate-800/70 p-4'}">\n        <span className="text-sm text-slate-300">${label}</span>\n      </div>`;
    default:
      return `      <div style={${style}} className="${cls || 'rounded-lg border border-white/10'}">${label}</div>`;
  }
}

function generateReactComponent(nodes: ExportCanvasNode[]): string {
  const jsx = nodes.map(nodeToReactJsx).join('\n');
  return `export default function GeneratedScreen() {\n  return (\n    <div className="relative min-h-screen bg-slate-950">\n${jsx}\n    </div>\n  );\n}\n`;
}

function nodeToFlutter(node: ExportCanvasNode): string {
  const { componentType, label, x, y, props } = node;
  const pos = `Positioned(left: ${x}, top: ${y},`;
  switch (componentType) {
    case 'button':
      return `    ${pos} child: ElevatedButton(onPressed: () {}, child: Text('${props.text ?? label}'))),`;
    case 'text':
      return `    ${pos} child: Text('${props.text ?? label}', style: const TextStyle(color: Colors.white))),`;
    case 'image':
      return `    ${pos} child: Image.network('${props.src ?? ''}')),`;
    default:
      return `    ${pos} child: Container(child: Text('${label}', style: const TextStyle(color: Colors.white)))),`;
  }
}

function generateFlutter(nodes: ExportCanvasNode[]): string {
  const widgets = nodes.map(nodeToFlutter).join('\n');
  return `import 'package:flutter/material.dart';\n\nvoid main() => runApp(const MyApp());\n\nclass MyApp extends StatelessWidget {\n  const MyApp({super.key});\n  @override\n  Widget build(BuildContext context) {\n    return MaterialApp(\n      home: Scaffold(\n        backgroundColor: const Color(0xFF0B1220),\n        body: Stack(\n          children: [\n${widgets}\n          ],\n        ),\n      ),\n    );\n  }\n}\n`;
}

function nodeToRN(node: ExportCanvasNode): string {
  const { componentType, label, props } = node;
  switch (componentType) {
    case 'button':
      return `      <TouchableOpacity style={styles.button}><Text style={styles.buttonText}>${props.text ?? label}</Text></TouchableOpacity>`;
    case 'text':
      return `      <Text style={styles.text}>${props.text ?? label}</Text>`;
    case 'image':
      return `      <Image source={{ uri: '${props.src ?? ''}' }} style={styles.image} />`;
    default:
      return `      <View style={styles.card}><Text style={styles.text}>${label}</Text></View>`;
  }
}

function generateRN(nodes: ExportCanvasNode[]): string {
  const components = nodes.map(nodeToRN).join('\n');
  return `import React from 'react';\nimport { ScrollView, View, Text, TouchableOpacity, Image, StyleSheet } from 'react-native';\n\nexport default function GeneratedScreen() {\n  return (\n    <ScrollView style={styles.root}>\n      <View style={styles.container}>\n${components}\n      </View>\n    </ScrollView>\n  );\n}\n\nconst styles = StyleSheet.create({\n  root: { flex: 1, backgroundColor: '#0B1220' },\n  container: { padding: 16 },\n  button: { backgroundColor: '#06b6d4', borderRadius: 6, padding: 10, marginVertical: 6 },\n  buttonText: { color: '#fff', fontWeight: '600', textAlign: 'center' },\n  text: { color: '#f1f5f9', marginVertical: 4 },\n  image: { width: '100%', height: 200, marginVertical: 6 },\n  card: { backgroundColor: '#1e293b', borderRadius: 8, padding: 12, marginVertical: 6 }\n});\n`;
}

export async function exportCanvas(payload: ExportCanvasPayload): Promise<ExportCanvasResult> {
  const { targetRoot, projectName, target, nodes } = payload;
  const overwrite = !!payload.overwrite;
  const created: string[] = [];
  try {
    const validated = validateProjectName(projectName);
    const projectRoot = path.join(targetRoot, validated);
    if (!overwrite && (await pathExists(projectRoot))) {
      return { ok: false, createdFiles: [], error: `Project folder '${validated}' already exists.` };
    }
    await ensureDir(projectRoot);

    if (target === 'react') {
      await writeGenerated(
        projectRoot,
        'package.json',
        JSON.stringify(
          {
            name: validated,
            version: '0.1.0',
            scripts: { dev: 'vite', build: 'vite build' },
            dependencies: { react: '^18.3.0', 'react-dom': '^18.3.0' },
            devDependencies: { vite: '^5.4.0', '@vitejs/plugin-react': '^4.3.0', typescript: '^5.6.0' }
          },
          null,
          2
        ),
        overwrite,
        created
      );
      await writeGenerated(
        projectRoot,
        'index.html',
        `<!doctype html>\n<html lang="en">\n  <head><meta charset="UTF-8" /><title>${validated}</title></head>\n  <body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body>\n</html>\n`,
        overwrite,
        created
      );
      await writeGenerated(
        projectRoot,
        'src/main.tsx',
        `import React from 'react';\nimport ReactDOM from 'react-dom/client';\nimport App from './App';\n\nReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);\n`,
        overwrite,
        created
      );
      await writeGenerated(projectRoot, 'src/App.tsx', generateReactComponent(nodes), overwrite, created);
    } else if (target === 'nextjs') {
      await writeGenerated(
        projectRoot,
        'package.json',
        JSON.stringify(
          {
            name: validated,
            version: '0.1.0',
            scripts: { dev: 'next dev', build: 'next build', start: 'next start' },
            dependencies: { next: '^14.2.0', react: '^18.3.0', 'react-dom': '^18.3.0' },
            devDependencies: { typescript: '^5.6.0', '@types/react': '^18.3.0' }
          },
          null,
          2
        ),
        overwrite,
        created
      );
      await writeGenerated(
        projectRoot,
        'next.config.js',
        `/** @type {import('next').NextConfig} */\nconst nextConfig = {};\nmodule.exports = nextConfig;\n`,
        overwrite,
        created
      );
      await writeGenerated(
        projectRoot,
        'app/layout.tsx',
        `export default function RootLayout({ children }: { children: React.ReactNode }) {\n  return <html lang="en"><body>{children}</body></html>;\n}\n`,
        overwrite,
        created
      );
      await writeGenerated(projectRoot, 'app/page.tsx', generateReactComponent(nodes), overwrite, created);
    } else if (target === 'flutter') {
      await writeGenerated(
        projectRoot,
        'pubspec.yaml',
        `name: ${validated.replace(/-/g, '_')}\ndescription: Generated by AetherForge IDE\nversion: 1.0.0+1\nenvironment:\n  sdk: '>=3.0.0 <4.0.0'\ndependencies:\n  flutter:\n    sdk: flutter\nflutter:\n  uses-material-design: true\n`,
        overwrite,
        created
      );
      await writeGenerated(projectRoot, 'lib/main.dart', generateFlutter(nodes), overwrite, created);
    } else if (target === 'react-native') {
      await writeGenerated(
        projectRoot,
        'package.json',
        JSON.stringify(
          {
            name: validated,
            version: '0.0.1',
            scripts: {
              start: 'react-native start',
              android: 'react-native run-android',
              ios: 'react-native run-ios'
            },
            dependencies: { react: '^18.3.0', 'react-native': '^0.74.0' },
            devDependencies: { typescript: '^5.6.0', '@types/react': '^18.3.0' }
          },
          null,
          2
        ),
        overwrite,
        created
      );
      await writeGenerated(projectRoot, 'App.tsx', generateRN(nodes), overwrite, created);
    }
    return { ok: true, projectPath: projectRoot, createdFiles: created };
  } catch (err) {
    return { ok: false, createdFiles: created, error: err instanceof Error ? err.message : 'Export failed' };
  }
}
